#include <QApplication>
#include <QMainWindow>
#include <QSplitter>
#include <QMenuBar>
#include <QVBoxLayout>
#include <QScrollArea>
#include <QLabel>
#include <QLineEdit>
#include <QFile>
#include <QTimer>
#include <QString>
#include <QStringLiteral>
#include <QtConcurrent>
#include <QStandardItem>
#include <QObject>
#include <QFileDialog>
#include <QFile>
#include <QMessageBox>
#include <QWidgetAction>